const $=s=>document.querySelector(s);const names={A:['封面光晕','模糊大图衬底 · 宋体标题 · 图片优先'],B:['封面色刊','封面取色 · 标题先行 · 横向信息栏'],C:['影像对页','深色封面取色 · 无衬线 · 图文并置']};
let fullTitle='35min 正念冥想｜把身体作为方法｜从内耗到感受｜此时此地此身｜聆听身体｜回归当下';names.B=['封面色刊 / 第三版','封面在上 · 独立标题区 · 共同对齐'];let variant='B';let cover='assets/cover.jpg',uploaded=false,palette=[];let toastTimer;
function notice(message){clearTimeout(toastTimer);$('#toast').textContent='原型演示：'+message+'（未写入剪贴板或下载）';$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function target(){let u=new URL('https://www.bilibili.com/video/BV1TXoWBsEGc/');if($('#part').checked)u.searchParams.set('p','1');if($('#time').checked)u.searchParams.set('t','83');return u.href}
function state(){let theme=document.body.classList.contains('dark')?'深色':'浅色';$('#state').textContent=`${theme}面板 · ${uploaded?'上传封面 / 元数据为样例':'历史视频样例'} · 分P ${$('#part').checked?'开':'关'} / 时间 ${$('#time').checked?'开':'关'} · 复制与下载仅演示`;}
function render(){const flags=($('#part').checked?'1':'0')+($('#time').checked?'1':'0');const mast='<div class="mast"><img class="brand" src="assets/bilibili-logo.svg" alt="哔哩哔哩"><div class="ids"><span>BV1TXoWBsEGc</span><span>av116448123027614</span></div></div>';const img='<img class="cover" src="'+cover+'" alt="海报封面">';const edit='<div class="editorial"><h2>'+fullTitle+'</h2></div>';const footer='<footer class="poster-footer"><div><div class="author"><img src="assets/up.svg" alt="UP 主">妮卡的房间NiCalm</div><div class="stats"><span><svg class="play-icon" viewBox="0 0 24 24" aria-label="播放"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m10 9 5 3-5 3z"/></svg>17.8万</span><span><img src="assets/like.svg" alt="点赞">2662</span><span><img src="assets/coin.svg" alt="投币">1285</span><span><img src="assets/fav.svg" alt="收藏">6656</span></div></div><div class="qr"><img src="assets/qr-original-'+flags+'.svg" alt="样例视频二维码">扫码观看</div></footer><div class="url">'+target()+'</div>';
$('#poster').className='poster variant-'+variant;$('#poster').innerHTML=mast+(variant==='A'?img+edit:variant==='B'?img+edit:'<div class="feature">'+edit+'<div class="cover-wrap">'+img+'</div></div>')+footer;
$('#copytext').textContent=fullTitle+'\n（UP主：妮卡的房间NiCalm）'+($('#details').checked?'\n播放 17.8万 · 点赞 2662\n投币 1285 · 收藏 6656':'');$('#copylink').textContent=target();$('#variant-label').textContent=variant+' — '+names[variant][0];$('#variant-note').textContent=names[variant][1];state();fitTitle();}
function cycle(){return;}
function mix(rgb,toward,amount){return rgb.map((c,i)=>Math.round(c*(1-amount)+toward[i]*amount))}function css(rgb){return 'rgb('+rgb.join(',')+')'}
async function sample(src){let im=new Image();im.src=src;await im.decode();const canvas=document.createElement('canvas');canvas.width=64;canvas.height=40;const cx=canvas.getContext('2d',{willReadFrequently:true});cx.drawImage(im,0,0,64,40);const d=cx.getImageData(0,0,64,40).data;const buckets=new Map();for(let i=0;i<d.length;i+=4){if(d[i+3]<200)continue;const rgb=[d[i],d[i+1],d[i+2]],l=rgb.reduce((a,b)=>a+b)/3;if(l<30||l>247)continue;const key=rgb.map(x=>Math.floor(x/32)).join(',');let b=buckets.get(key)||{n:0,r:[0,0,0]};b.n++;rgb.forEach((v,j)=>b.r[j]+=v);buckets.set(key,b)}let sorted=[...buckets.values()].sort((a,b)=>b.n-a.n);const base=sorted[0]?sorted[0].r.map(v=>Math.round(v/sorted[0].n)):[128,128,128];let colorful=sorted.slice(0,12).sort((a,b)=>{const sat=z=>(Math.max(...z.r)-Math.min(...z.r))/z.n;return sat(b)-sat(a)})[0];const accent=colorful?colorful.r.map(v=>Math.round(v/colorful.n)):base;const ink=mix(accent,[12,16,20],.8),paper=mix(base,[255,255,255],.60),soft=mix(base,[255,255,255],.25);palette=[ink,paper,accent,soft];['--poster-ink','--poster-base','--poster-accent','--poster-soft'].forEach((key,i)=>document.documentElement.style.setProperty(key,css(palette[i])));document.documentElement.style.setProperty('--cover',`url("${src}")`);const bg=document.createElement('canvas');bg.width=240;bg.height=320;const bc=bg.getContext('2d');bc.filter='blur(18px)';const scale=Math.max(280/im.width,360/im.height);bc.drawImage(im,(240-im.width*scale)/2,(320-im.height*scale)/2,im.width*scale,im.height*scale);document.documentElement.style.setProperty('--blurred-cover',`url("${bg.toDataURL()}")`);$('#palette').innerHTML=palette.map(c=>'<i title="'+css(c)+'" style="background:'+css(c)+'"></i>').join('');render()}
$('#prev').onclick=()=>cycle(-1);$('#next').onclick=()=>cycle(1);addEventListener('keydown',e=>{if(e.target.closest('input,textarea,[contenteditable]'))return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1)});$('#theme').onclick=()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'切换浅色':'切换深色';state()};for(const id of ['part','time','details'])$('#'+id).onchange=render;document.querySelectorAll('[data-notice]').forEach(el=>el.onclick=()=>notice(el.dataset.notice));$('#close').onclick=()=>{$('.panel').hidden=true;$('#entry').focus()};$('#entry').onclick=()=>{$('.panel').hidden=false;$('#panel-title').scrollIntoView({block:'start',behavior:'instant'})};$('#upload').onchange=()=>{const file=$('#upload').files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{cover=reader.result;uploaded=true;await sample(cover)};reader.readAsDataURL(file)};$('#reset').onclick=()=>{cover='assets/cover.jpg';uploaded=false;$('#upload').value='';sample(cover)};render();sample(cover);

function fitTitle(){const box=document.querySelector('.editorial'),h=box.querySelector('h2');const w=document.querySelector('#poster').getBoundingClientRect().width;const room=w*.26*4/3-parseFloat(getComputedStyle(box).paddingTop)-parseFloat(getComputedStyle(box).paddingBottom);const probe=h.cloneNode(false);probe.removeAttribute('id');Object.assign(probe.style,{position:'fixed',visibility:'hidden',pointerEvents:'none',left:'-10000px',top:'0',width:h.getBoundingClientRect().width+'px',height:'auto',margin:'0'});box.append(probe);let selected=4.4,result=fullTitle;try{probe.textContent=fullTitle;let fits=false;for(const size of [6.0,5.6,5.2,4.8,4.4]){probe.style.fontSize=(w*size/100)+'px';selected=size;if(probe.scrollHeight<=room+1){fits=true;break;}}if(!fits){const chars=Array.from(fullTitle);let lo=0,hi=chars.length;while(lo<hi){const mid=Math.ceil((lo+hi)/2);probe.textContent=chars.slice(0,mid).join('')+'…';if(probe.scrollHeight<=room+1)lo=mid;else hi=mid-1;}result=chars.slice(0,lo).join('')+'…';}}finally{probe.remove();}h.style.fontSize=(w*selected/100)+'px';h.textContent=result;}

const titles={short:'把身体作为方法',normal:'35min 正念冥想｜把身体作为方法｜从内耗到感受｜此时此地此身｜聆听身体｜回归当下',long:'从清晨到深夜，重新认识身体与注意力：一段关于正念、日常生活、城市漫步与内心安定的完整记录，尝试在复杂的信息里找回自己的节奏。',extreme:'超长标题压力样例：'+('在日常生活中重新发现身体、空间与时间的关系，').repeat(12)};
document.querySelector('#title-case').onchange=e=>{fullTitle=titles[e.target.value];render()};
document.querySelector('#cover-case').onchange=async e=>{if(e.target.value==='wide'){cover='assets/cover.jpg';uploaded=false;}else{const width=e.target.value==='square'?600:400,height=e.target.value==='square'?600:800;const svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+width+'" height="'+height+'"><rect width="100%" height="100%" fill="#94462e"/><circle cx="'+width*.6+'" cy="'+height*.3+'" r="'+width*.32+'" fill="#e9bd70"/><path d="M0 '+height+' L0 '+height*.65+' L'+width*.4+' '+height*.5+' L'+width+' '+height+' Z" fill="#433139"/><text x="24" y="'+(height-35)+'" fill="white" font-size="24">'+width+' × '+height+' TEST</text></svg>';cover='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);uploaded=true;}await sample(cover);};
new ResizeObserver(()=>fitTitle()).observe(document.querySelector('#poster'));document.fonts.ready.then(fitTitle);
