const $=s=>document.querySelector(s);const names={A:['封面光晕','模糊大图衬底 · 宋体标题 · 图片优先'],B:['封面色刊','封面取色 · 标题先行 · 横向信息栏'],C:['影像对页','深色封面取色 · 无衬线 · 图文并置']};
const fullTitle='35min 正念冥想｜把身体作为方法｜从内耗到感受｜此时此地此身｜聆听身体｜回归当下';let variant=new URLSearchParams(location.search).get('variant')||'A';if(!names[variant])variant='A';let cover='assets/cover.jpg',uploaded=false,palette=[];let toastTimer;
function notice(message){clearTimeout(toastTimer);$('#toast').textContent='原型演示：'+message+'（未写入剪贴板或下载）';$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function target(){let u=new URL('https://www.bilibili.com/video/BV1TXoWBsEGc/');if($('#part').checked)u.searchParams.set('p','1');if($('#time').checked)u.searchParams.set('t','83');return u.href}
function state(){let theme=document.body.classList.contains('dark')?'深色':'浅色';$('#state').textContent=`${theme}面板 · ${uploaded?'上传封面 / 元数据为样例':'历史视频样例'} · 分P ${$('#part').checked?'开':'关'} / 时间 ${$('#time').checked?'开':'关'} · 复制与下载仅演示`;}
function render(){const flags=($('#part').checked?'1':'0')+($('#time').checked?'1':'0');const mast='<div class="mast"><img class="brand" src="assets/bilibili-logo.svg" alt="哔哩哔哩"><div class="ids"><span>BV1TXoWBsEGc</span><span>av116448123027614</span></div></div>';const img='<img class="cover" src="'+cover+'" alt="海报封面">';const edit='<div class="editorial"><h2>'+fullTitle+'</h2></div>';const footer='<footer class="poster-footer"><div><div class="author"><img src="assets/up.svg" alt="UP 主">妮卡的房间NiCalm</div><div class="stats"><span>▷ 17.8万</span><span><img src="assets/like.svg" alt="点赞">2662</span><span><img src="assets/coin.svg" alt="投币">1285</span><span><img src="assets/fav.svg" alt="收藏">6656</span></div></div><div class="qr"><img src="assets/qr-original-'+flags+'.svg" alt="样例视频二维码">扫码观看</div></footer><div class="url">'+target()+'</div>';
$('#poster').className='poster variant-'+variant;$('#poster').innerHTML=mast+(variant==='A'?img+edit:variant==='B'?edit+img:'<div class="feature">'+edit+'<div class="cover-wrap">'+img+'</div></div>')+footer;
$('#copytext').textContent=fullTitle+'\n（UP主：妮卡的房间NiCalm）'+($('#details').checked?'\n播放 17.8万 · 点赞 2662\n投币 1285 · 收藏 6656':'');$('#copylink').textContent=target();$('#variant-label').textContent=variant+' — '+names[variant][0];$('#variant-note').textContent=names[variant][1];state();}
function cycle(delta){variant='ABC'[('ABC'.indexOf(variant)+delta+3)%3];const u=new URL(location.href);u.searchParams.set('variant',variant);history.replaceState(null,'',u);render()}
function mix(rgb,toward,amount){return rgb.map((c,i)=>Math.round(c*(1-amount)+toward[i]*amount))}function css(rgb){return 'rgb('+rgb.join(',')+')'}
async function sample(src){let im=new Image();im.src=src;await im.decode();const canvas=document.createElement('canvas');canvas.width=64;canvas.height=40;const cx=canvas.getContext('2d',{willReadFrequently:true});cx.drawImage(im,0,0,64,40);const d=cx.getImageData(0,0,64,40).data;const buckets=new Map();for(let i=0;i<d.length;i+=4){if(d[i+3]<200)continue;const rgb=[d[i],d[i+1],d[i+2]],l=rgb.reduce((a,b)=>a+b)/3;if(l<30||l>247)continue;const key=rgb.map(x=>Math.floor(x/32)).join(',');let b=buckets.get(key)||{n:0,r:[0,0,0]};b.n++;rgb.forEach((v,j)=>b.r[j]+=v);buckets.set(key,b)}let sorted=[...buckets.values()].sort((a,b)=>b.n-a.n);const base=sorted[0]?sorted[0].r.map(v=>Math.round(v/sorted[0].n)):[128,128,128];let colorful=sorted.slice(0,12).sort((a,b)=>{const sat=z=>(Math.max(...z.r)-Math.min(...z.r))/z.n;return sat(b)-sat(a)})[0];const accent=colorful?colorful.r.map(v=>Math.round(v/colorful.n)):base;const ink=mix(accent,[12,16,20],.8),paper=mix(base,[255,255,255],.60),soft=mix(base,[255,255,255],.25);palette=[ink,paper,accent,soft];['--poster-ink','--poster-base','--poster-accent','--poster-soft'].forEach((key,i)=>document.documentElement.style.setProperty(key,css(palette[i])));document.documentElement.style.setProperty('--cover',`url("${src}")`);$('#palette').innerHTML=palette.map(c=>'<i title="'+css(c)+'" style="background:'+css(c)+'"></i>').join('');render()}
$('#prev').onclick=()=>cycle(-1);$('#next').onclick=()=>cycle(1);addEventListener('keydown',e=>{if(e.target.closest('input,textarea,[contenteditable]'))return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1)});addEventListener('popstate',()=>{variant=new URLSearchParams(location.search).get('variant')||'A';if(!names[variant])variant='A';render()});$('#theme').onclick=()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'切换浅色':'切换深色';state()};for(const id of ['part','time','details'])$('#'+id).onchange=render;document.querySelectorAll('[data-notice]').forEach(el=>el.onclick=()=>notice(el.dataset.notice));$('#close').onclick=()=>{$('.panel').hidden=true;$('#entry').focus()};$('#entry').onclick=()=>{$('.panel').hidden=false;$('#panel-title').scrollIntoView({block:'start',behavior:'instant'})};$('#upload').onchange=()=>{const file=$('#upload').files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{cover=reader.result;uploaded=true;await sample(cover)};reader.readAsDataURL(file)};$('#reset').onclick=()=>{cover='assets/cover.jpg';uploaded=false;$('#upload').value='';sample(cover)};render();sample(cover);
