const $=s=>document.querySelector(s), params=new URLSearchParams(location.search);
const selector=$('#case');for(const [key,f] of Object.entries(FIXTURES)){const option=new Option(f.name,key);selector.add(option)}
selector.value=params.get('case') in FIXTURES?params.get('case'):'original';
$('#state').value=params.get('state')||'ready';
let fixture=FIXTURES[selector.value];
function scale(){ document.documentElement.style.setProperty('--lab-height',$('.lab').offsetHeight+'px');document.documentElement.style.setProperty('--lab-foot-height',$('.lab-foot').offsetHeight+'px');$('#poster').style.transform=`scale(${$('.preview-frame').clientWidth/1080})`; }
window.addEventListener('resize',scale);scale();
function renderText(){const full=$('#detail').checked;let body=fixture.title;if(full)body='UP 主：'+fixture.uploader+'\n'+body+'\n播放 178,000 · 点赞 2,662 · 投币 1,285 · 收藏 6,656';if($('#markdown').checked){$('#text-body').textContent=full?body:'['+fixture.title+']('+fixture.target+')';$('#text-link').textContent=full?'[观看视频]('+fixture.target+')':''}else{$('#text-body').textContent=body;$('#text-link').textContent=fixture.target}}
function chooseCase(){fixture=FIXTURES[selector.value];$('#poster').src='poster.html?case='+selector.value;$('#part').checked=!!fixture.part;$('#time').checked=!!fixture.time;$('#target-note').textContent=fixture.part?fixture.part.split(' · ')[0]+(fixture.time?' · '+fixture.time:''):fixture.time?'从 '+fixture.time+' 开始播放':'默认从视频开头播放';$('#case-note').textContent=fixture.synthetic?'合成边界样例，仅验证排版；不代表真实视频元数据或已验证播放落点。':'真实标题与原始封面；统计沿用已批准原型历史快照。';$('#inspect').href='poster.html?case='+selector.value;renderText();const url=new URL(location.href);url.searchParams.set('case',selector.value);history.replaceState(null,'',url);}
function renderState(){const state=$('#state').value,blocked=['loading','updating','error'].includes(state);$('#preview-state').hidden=!blocked;$('#preview-state').classList.toggle('updating',state==='updating');$('#preview-message').textContent=state==='loading'?'正在生成海报':state==='updating'?'正在更新观看起点':'暂时无法生成预览';$('.spinner').hidden=state==='error';$('#generation-error').hidden=state!=='error';$('#fallback').hidden=state!=='fallback';$('#status').classList.toggle('error',state==='copyfailed');$('#status').textContent=state==='copyfailed'?'海报复制失败，请使用“下载 PNG”保存图片。':'';for(const id of ['copy-poster','download','copy-text','combined','part','time','detail','markdown'])$('#'+id).disabled=blocked;const url=new URL(location.href);url.searchParams.set('state',state);history.replaceState(null,'',url)}
selector.addEventListener('change',chooseCase);$('#state').addEventListener('change',renderState);
for(const id of ['detail','markdown'])$('#'+id).addEventListener('change',renderText);
for(const id of ['part','time'])$('#'+id).addEventListener('change',()=>{let p=$('#part').checked,t=$('#time').checked;const laterPart=!!fixture.part;if(id==='part'&&!p)t=false;if(id==='time'&&t&&laterPart)p=true;selector.value=p?(t?'part':'partonly'):(t?'timeonly':'original');chooseCase();$('#status').textContent='原型演示：切换到预设的观看起点样例。'});
for(const [id,verb] of [['copy-poster','复制海报'],['copy-text','复制文案'],['download','下载 PNG'],['combined','组合复制']])$('#'+id).addEventListener('click',()=>{$('#status').classList.remove('error');$('#status').textContent='原型演示：'+verb+'反馈；未操作剪贴板或下载。'});
$('#retry').addEventListener('click',()=>{$('#state').value='ready';renderState();$('#status').textContent='原型演示：重新生成后的完成状态。'});
function close(){$('#backdrop').hidden=true;$('#entry').focus()}
function open(){$('#backdrop').hidden=false;scale();$('.panel').focus()}
$('#close').addEventListener('click',close);$('#entry').addEventListener('click',open);$('#backdrop').addEventListener('click',e=>{if(e.target===$('#backdrop'))close()});
document.addEventListener('keydown',e=>{if($('#backdrop').hidden)return;if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const nodes=[...$('.panel').querySelectorAll('button:not(:disabled),input:not(:disabled),summary,[tabindex="0"]')].filter(n=>n.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.panel'))){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function appearance(dark){document.body.classList.toggle('dark',dark);$('#appearance').textContent=dark?'模拟浅色页面':'模拟深色页面';const url=new URL(location.href);url.searchParams.set('appearance',dark?'dark':'light');history.replaceState(null,'',url)}
$('#appearance').addEventListener('click',()=>appearance(!document.body.classList.contains('dark')));appearance(params.get('appearance')==='dark');
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('#poster').contentWindow||e.data.type!=='poster-ready')return;const r=e.data.report;$('#metrics').textContent=`标题 ${r.titleSize}px${r.titleTruncated?' / 已省略':''} · 昵称 ${r.nameSize}px${r.nameTruncated?' / 已省略':''} · 页脚 ${r.linkHeight}px`;scale()});
chooseCase();renderState();if(params.get('entry')==='1')close();else $('.panel').focus();
